export const dataTableHeadings = [
  'Date',
  'Product',
  'Cows',
  'Quantity',
  'Meter',
  'Water usage',
  'Water intake',
  'Pump',
  'Before float',
  'kg actual',
  'Target feed',
  'Actual feed',
  'After float',
  'Next delivery',
  'Comments',
];
